[build]
  publish = "mpp"  # Root folder for the build is mpp/ (this includes public/ and fun/)

# Redirects for public/ folder (for static content)
[[redirects]]
  from = "/public/*"
  to = "/mpp/public/:splat"
  status = 200
  force = true

# Redirects for fun/ folder (for other content)
[[redirects]]
  from = "/fun/*"
  to = "/mpp/fun/:splat"
  status = 200
  force = true
