[build]
  # Tell Netlify to use the public folder as the root directory for serving files
  publish = "public"

  # Optional: If you need to run a build command, add it here (e.g., for compiling assets)
  command = "echo 'no build'"

[[redirects]]
  # Optionally redirect any other paths to the public folder
  from = "/*"
  to = "/:splat"
  status = 200
  force = true
