[build]
  # Set the folder to publish as the root of your project
  publish = "/"

  # Optional: Add a build command if you need it (e.g., for compiling assets)
  command = "echo 'no build'"

[[redirects]]
  from = "/mpp/*"
  to = "/mpp/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/fun/*"
  to = "/fun/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/protocol/*"
  to = "/protocol/:splat"
  status = 200
  force = true
