[build]
  # Set the folder to publish as the root of your project
  publish = "/"

  # Optional: Add a build command if you need it (e.g., for compiling assets)
  # If no build is required, you can leave it out or set it as "echo 'no build'"
  command = "echo 'no build'"

[[redirects]]
  from = "/mpp/*"
  to = "/mpp/:splat"
  status = 200
  force = true
